<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<module category="OD Sample" descriptorversion="1.0" entrypoint="FoodPlaza/Start" forcesubdialogcall="false" frameworkversion="07.21.05.02" iconlarge="icons/defaultapplicationlg.gif" iconsmall="icons/defaultapplicationsm.gif" modifyInputs="false" modifyOutputs="false" nature="com.avaya.sce.core.speechnature" outputmultipart="false" paramasnamelist="false" provider="AVAYA" submitmethod="get" version="1.0.0" webname="FoodPlaza">
    <description/>
    <language name="english" root="en-us"/>
    <dependencies/>
</module>
