package connectivity.ws.operations;

/**
 * This class is generated automatically.  Manual edits must be outside of the tagged
 * areas (for example, "START:CLASS:..." and "END:CLASS:...").  Changes within the
 * tag areas will be overwritten when the web service operation is regenerated.
 * Last generated by Orchestration Designer at: 2019-JUN-18  04:12:03 PM
 */
public class Demo extends com.avaya.sce.runtime.connectivity.restws.CallService {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

    /**
    * Constructor for Demo.
    */
    public Demo( com.avaya.sce.runtimecommon.IRuntimeSession mySession ) {
		//{{START:CLASS:CONSTRUCTOR
        super(mySession);

        //Web Service
        setServiceName("Demo");
		setHttpMethod("GET");
		setOutputFormat("Server Default");
		setUseQuery("true");
		setUseJavaObject("true");
		setUseBody("false");
        setTimeoutSecondsFromParameter("Demo_1560854523742TimeoutSeconds");
        setEndpointFromParameter("Demo_1560854523742EndpointUrl");
        setAuthenticationFromParameter("Demo_1560854523742Authentication");
        setPasswordFromParameter("Demo_1560854523742Password");
        setUsernameFromParameter("Demo_1560854523742Username");
        setPreemptiveFromParameter("Demo_1560854523742Preemptive");
        setSecurityFromParameter("Demo_1560854523742Security");
        setPortFromParameter("Demo_1560854523742Port");

        //Operation
        setOperation(new javax.xml.namespace.QName("", "Demo_OP"));

        //Input parameters

        //Output parameters
		setMessageBody("");
        //}}END:CLASS:CONSTRUCTOR









    }

}

